### ISSUE TITLE
Database setup and server implementation

### ISSUE THREAD

**Issue by BishanWebeshete** [BishanWebeshete/Retail-Rater#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
- This will be just to set up the application

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Follow the instructions on creating/testing full project setup
- [x] After following the guidelines set up the server.js file
     -  [x] create server.js
     -  [x] app.listen on process.evn.PORT
     -  [x] app.use(express)
     - [x] app.use(express.static('public')
     - [x] app.use(cors({origin: '*'})
     - [x] include pg
- [x] Right now focus on restaurant routes... will implement review routes later
     - [x] get route for /api/restaurants
     -  [x] get route for /api/restaurants/:id
     - [x] post route for /api/restaurants
     - [x] put route for api/restaurants/:id
     - [x] delete route for api/restaurants/:id 
 - [x] query db properly with its respective route to manipulate db

### 🧑‍⚕️ Clean Up Tasks
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
