### ISSUE TITLE
user-can-view-details

### ISSUE THREAD

**Issue by BishanWebeshete** [BishanWebeshete/Retail-Rater#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

- [x] create a handeRestaurantClick function which uses the navigate hook to take the user to the restaurant details page
- [x] use an arrow function on the onClick event handler of the tr which contains the restaurant
- [x] update handleUpdate and handleDelete functions to use e.stopPropagation so that when the delete and update buttons are clicked they will not just go to the details page
- [x] update use context to include selected/setSelectedRestaurant
- [x] In the restaurantDetails route/page fetch data on that specific restaurantId and set the response object as the selectedRestaurant
- [x] create a StarRating component
- [x] update starRating component to push either a full, half , or empty star depending on what rating was inputted by the user
- [x] create Reviews component which contains the cards with reviewer name, rating, and comments
- [x] create AddReview component which is a form where user can submit their review
- [x] update server.js to accomadate for reviews as well 
- [x] update details page to display all reviews for that specific restaurant

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
