### ISSUE TITLE
routing-and-home-page

### ISSUE THREAD

**Issue by BishanWebeshete** [BishanWebeshete/Retail-Rater#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Tasks

- [x] Make sure react app is set up properly
    - [x] Index.js and App.js are imported/exported properly 
- [x] Install Bootstrap
- [x] Install Fontawesome
- [x] install react-router-dom
- [x] create routes for home, restaurant detail, and update-restaurant page
- [x] create components folder which contain all three components for the home page
     - [x] Header, form where you can add a restaurant, and list of inputted restaurants
- [x] For now, in the restaurants list create dummy data in your table to make sure everything is displaying properly
- [x] useContext to store the data so that all of the components can have access to the data
- [x] create a new file which will store the restaurants context
- [x] useContext to store an array of all the restaurants in the database
- [x] use fetch to retrieve data from database and display the items
- [x] useContext to store the info without having to pass through props too many times

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
